services:
  keeper1:
    image: clickhouse/clickhouse-keeper:25.4.3
    hostname: keeper1
    container_name: keeper1
    volumes:
      - ./configs/keeper1.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
    
  keeper2:
    image: clickhouse/clickhouse-keeper:25.4.3
    hostname: keeper2
    container_name: keeper2
    volumes:
      - ./configs/keeper2.xml:/etc/clickhouse-keeper/keeper_config.xml:ro

  keeper3:
    image: clickhouse/clickhouse-keeper:25.4.3
    hostname: keeper3
    container_name: keeper3
    volumes:
      - ./configs/keeper3.xml:/etc/clickhouse-keeper/keeper_config.xml:ro

  clickhouse1:
    image: clickhouse/clickhouse-server:25.4.3
    hostname: clickhouse1
    container_name: clickhouse1
    depends_on: [keeper1, keeper2, keeper3]
    volumes:
      - ./configs/server1.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./logs-ch1:/var/log/clickhouse-server:rw

  clickhouse2:
    image: clickhouse/clickhouse-server:25.4.3
    hostname: clickhouse2
    container_name: clickhouse2
    depends_on: [keeper1, keeper2, keeper3]
    volumes:
      - ./configs/server2.xml:/etc/clickhouse-server/config.d/config.xml:ro
      - ./logs-ch2:/var/log/clickhouse-server:rw
